export const API_CACHE_KEY = {
  LOGIN: 'login',
  SEND_OTP: 'send-otp',
  VERIFY_OTP: 'verify-otp',
  GET_EMPLOYEE_LIST:"get-employee-list",
  VERIFY_FORGOT_PASSWORD: 'verify-forgot-password',
  SIGNUP:'sign-up',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  GET_MANAGER_LOG_LIST: 'get-manager-log-list',
  GET_LOG_ENTRIES: 'get-log-entries',
  ADD_NEW_LOG: 'add-new-log',
  UPDATE_LOG: 'update-log',
  DELETE_LOG: 'delete-log',
  GET_ORGANIZATION_FACILITIES: 'get-organization-facilities',
  GET_ORGANIZATION_POSITIONS: 'get-organization-department-positions',
  GET_ORGANIZATION_FACILITIES_DEPARTMENT:
    'get-organization-facilities-department',
  GET_MANAGER_LOG_SETTING: 'get-manager-log-setting',
  GET_USER_LIST: 'get-user-list',
  GET_USER_PROFILE: 'get-user-profile',
  DELETE_USER: 'delete-user',
  GET_FACILITY_EMPLOYEES: 'get-facility-employees',
  ADD_NEW_SETTING_MODULE: 'add-new-log-setting',
  DELETE_SETTING_MODULE: 'delete-log-setting',
  GET_LOG_DETAIL: 'get-log-detail',
  UPDATE_SETTING_SUBSCRIBERS: 'update-log-setting-subscribers',
  UPDATE_MODULE_BULK: 'update-module-bulk',
  UPLOAD_FILE: 'upload-file',
  GET_USER_UPLOAD_FILE: 'get-user-upload-file',
  DELETE_USER_FILE: 'delete-user-file',
  DELETE_LOG_ENTRY: 'delete-log-entry',
  ADD_NEW_LOG_ENTRY: 'add-new-log-entry',
  UPDATE_LOG_ENTRY: 'update-log-entry',
  UPDATE_TAGS: 'update-tags',
  PREVIEW_LINK: 'preview-link',
  CREATE_REPORT: 'create-report',
  GET_FEEDBACK_LIST: 'get-feedback-list',
  ADD_FEEDBACK: 'add-feedback',
  GET_MEDIA_LIST: 'get-media-list',
  DELETE_MEDIA: 'delete-media',
  GET_MEDIA_COMMENTS: 'get-media-comments',
  CREATE_MEDIA_COMMENT: 'create-media-comment',
  DELETE_MEDIA_COMMENT: 'delete-media-comment',
  GET_FACILITY_TOTAL_STATS: 'get-facility-total-stats',
  GET_FACILITY_STATISTICS: 'get-facility-statistics',
  
  GET_ORGANIZATION_LIST: 'get-organization-list',
  GET_ORGANIZATION_ALL_LIST: 'get-organization-all-list',
  ADD_NEW_ORGANIZATION: 'add-new-organization',
  UPDATE_ORGANIZATION: 'update-organization',
  GET_DETAILS_ORGANIZATION: 'get-details-organization',
  
  GET_RESTAURANT_LIST: 'get-restaurant-list',
  GET_RESTAURANT_ALL_LIST: 'get-restaurant-all-list',
  ADD_NEW_RESTAURANT: 'add-new-restaurant',
  UPDATE_RESTAURANT: 'update-restaurant',
  GET_DETAILS_RESTAURANT: 'get-details-restaurant',
  DELETE_RESTAURANT: 'delete-restaurant',
  
  GET_FACILITY_GROUP_LIST: 'get-faciltyGroup-list',
  GET_DETAILS_FACILITY_GROUP: 'get-details-faciltyGroup',
  GET_FACILITY_GROUP_FACILITIES: 'get-faciltyGroup-facilities',
  DELETE_FACILITY_GROUP: 'delete-faciltyGroup',

  ADD_NEW_FACILITY: 'add-new-facility',
  UPDATE_FACILITY: 'update-facility',
  DELETE_FACILITY: 'delete-facility',
  GET_DETAILS_FACILITY: 'get-details-facility',
  
  ADD_NEW_DEPARTMENT: 'add-new-department',
  UPDATE_DEPARTMENT: 'update-department',
  DELETE_DEPARTMENT: 'delete-department',
  GET_DETAILS_DEPARTMENT: 'get-details-department',
  
  ADD_NEW_POSITION: 'add-new-position',
  UPDATE_POSITION: 'update-position',
  DELETE_POSITION: 'delete-position',
  GET_DETAILS_POSITION: 'get-details-position',
  EMPLOYEE_DELETE:'employee-delete',
  EMPLOYEE_UPDATE:'employee-update'

} as const;
